---
kind: pipeline
name: testing

clone:
  depth: 50

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: lint
    image: golang:1.11
    pull: always
    commands:
      - go tool vet -all -shadowstrict .
      - go get -u github.com/mgechev/revive
      - revive -config .revive.toml -exclude=./vendor/... ./...

  - name: test
    image: golang:1.11
    pull: always
    commands:
      - go test -v .
      - go vet
